### ISSUE TITLE
The one vehicle limit price-point/threshold is slightly off.

### ISSUE THREAD

**Issue by SeseelLybon** [Arsonide/GTABusinessmate#3]
In the app you have markers of where the threshold is when you need only 1 vehicle. However, this is a little off. This is more of a min-max thing, though.

The real threshold is 1 bar + 1 step of produce. For Coke this is 1.5 bars. Because coke is produced in steps of 0.5: 1 bar + 1 step (0.5) = 1.5.

(capacity/bars)+1=steps of produce
(sell/capacity)*steps of produce = actual threshold for 1 vehicle.

-  Forgery: (60/5)+1=13
(84/60)*13=23.7997k
-  Weed: (80/5)+1=17
(168/80)*17=18.9002k
-  Counterfeit: (40/5)+1=9
(196/40)*9=44.1k
-  Meth: (20/5)+1=5
(238/20)*5=59.5k
-  Coke: (10/5)+1=3
(280/10)*3=84.0k

Sources:
-  Own experiance with meth, coke and counterfeit.
-  https://docs.google.com/spreadsheets/d/1mX8wGG1Oy76nhv-tBZ-oPmKiynng8fMS87EMxmoyB0Y/edit#gid=164058077

[Edit]
Upon re-checking if the things I mentoined were true, I noticed that I'm mistaken.
Appearantly they are all within a few 1000 of the thresholds I mentioned.
Pardon me. I have no idea where the confusion happened. -.-'

**Comment by Arsonide** [comment]
The one vehicle threshold is apparently always 25% of a full sale value, so that particular marker is just offset by a normalized value of 0.25, and doesn't even take ticks or sale amounts into account. This seems to be fairly accurate, but it's also in the configuration file.

The incongruities you are noticing are likely due to the fact that when sliding the product bar it is rounded by $1000, and the fact that the ticks in the game themselves are fairly nebulous, as opposed to the smoothly calculated values of Businessmate.
